name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - "feature/*"
      - "bugfix/*"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Gunakan Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: |
          npm ci

      - name: Jalankan Uji Komponen
        run: |
          npm test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Pastikan job ini hanya berjalan untuk branch main

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login ke Docker Hub dengan debug
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled  # Mengaktifkan debugging

      - name: Build dan Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .  # Menunjukkan lokasi konteks build
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/portfolio-testing:latest
            ${{ secrets.DOCKER_USERNAME }}/portfolio-testing:${{ github.sha }}
