name: CI/CD for React App Danendra

on:
  push:
    branches:
      - main
      - master
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - main
      - master
      - feature/*
      - bugfix/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:verbose