name: CI/CD 


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
           node-version: "20.17.0"

  
      - name: Install dependencies
        run: npm install

  
      - name: Run tests
        run: npm test -- --ci --coverage --watchAll=false
        env:
          CI: true

    
      - name: Build React App
        run: npm run build