name: CI/CD Pipeline

on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

  
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
        node-version: '20.17.0' 

    
      - name: Install dependencies
        run: npm install

    
      - name: Run tests
        run: npm test -- --ci --coverage

     
      - name: Build Docker image
        run: |
          docker build -t my-docker-image .
          docker tag my-docker-image myusername/my-docker-image:latest

    
      - name: Push Docker image to Docker Hub
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker push myusername/my-docker-image:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build 
    steps:
     
      - name: Checkout code
        uses: actions/checkout@v2

     
      - name: Deploy to server
        run: |
          # Ganti dengan perintah deploy yang sesuai dengan aplikasi atau servermu
          echo "Deploying app..."
